// ── DATA ─────────────────────────────────────────────────

export const NAV_CATS = [
  { id: "drama",  label: "DRAMA"  },
  { id: "film",   label: "FILM"   },
  { id: "music",  label: "MUSIC"  },
  { id: "beauty", label: "BEAUTY" },
  { id: "food",   label: "FOOD"   },
  { id: "place",  label: "PLACE"  },
];

export const NAV_SECTIONS = [
  { id: "edit",  label: "THE EDIT"   },
  { id: "trail", label: "ALL TRAILS" },
];

export const ARTICLES = [
  { id:1, cats:["music"], type:"article", views:11200, title:"BTS Made These Places Famous. But They Were Always There.", sub:"On the difference between a filming location and a place with a soul.", time:"7 min read", imgH: 320, thumb:"https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=600&q=80", body:["Iryeong Station had been abandoned for two decades before 'Spring Day' arrived. The tracks were overgrown. The platform was crumbling. The stationmaster had long since moved away.","Then BTS filmed there, and the world found out the station existed. Now ARMY members from every continent make the journey to Yangju — not for the drama of arrival, but for the specific quality of silence the place holds.","We spoke to the last stationmaster's daughter. 'They come because they feel something here,' she said. 'That feeling was always here. The song just helped them find it.'"] },
  { id:2, cats:["drama"], type:"article", views:9420, title:"Crash Landing on You Changed Bukchon Forever", sub:"How one drama turned a quiet hanok neighbourhood into a global destination.", time:"6 min read", imgH: 240, thumb:"https://images.unsplash.com/photo-1548115184-bc6544d06a58?w=600&q=80", body:["Before Son Ye-jin walked those alleys on screen, Bukchon was beloved but local. After the drama aired, everything changed.","The residents found themselves sharing their mornings with visitors from Bangkok, São Paulo, and Los Angeles.","ATO spoke to a third-generation hanok owner about what it means to live inside someone else's dream of Korea."] },
  { id:3, cats:["film"], type:"article", views:8710, title:"Why the World Can't Stop Visiting Parasite Locations", sub:"Bong Joon-ho used real Seoul streets. Here's what they mean to locals.", time:"8 min read", imgH: 280, thumb:"https://images.unsplash.com/photo-1607893378714-007fd47c8719?w=600&q=80", body:["Four years after Parasite swept the Oscars, the alleyways of Mapo-gu have become unlikely pilgrimage sites.","The Daejissal Supermarket still operates. Every week, someone stops to bow slightly, as if paying respects.","Bong Joon-ho chose these locations because they felt invisible to most Seoulites."] },
  { id:4, cats:["place"], type:"article", views:8100, title:"Cherry Blossom Season: The Insider Timeline", sub:"When to go, where to stand, and what everyone else gets wrong.", time:"5 min read", imgH: 200, thumb:"https://images.unsplash.com/photo-1522383225653-ed111181a951?w=600&q=80", body:["The crowds at Yeouido are real. But so are the empty paths at Changdeokgung Palace at 7am, with petals falling on nobody but you.","Cherry blossom season in Seoul lasts approximately ten days. The window is narrow.","We consulted the Korea Meteorological Administration's data and spoke to three Seoul-based photographers."] },
  { id:5, cats:["beauty"], type:"article", views:7830, title:"The K-Beauty Pilgrim's Map", sub:"From Olive Young to niche skincare labs — where locals actually shop.", time:"6 min read", imgH: 360, thumb:"https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=600&q=80", body:["Every traveller leaves Seoul with a suitcase heavier than they planned.","In Seongsu-dong, a converted warehouse sells skincare developed by a former cosmetic chemist who left a major conglomerate.","We spent three days with a Seoul-based beauty editor, visiting the places that don't appear in tourist guides."] },
  { id:6, cats:["music","place"], type:"article", views:7200, title:"Han River After Dark: The Music Video Seoul", sub:"Why every K-Pop director eventually shoots on the water.", time:"5 min read", imgH: 260, thumb:"https://images.unsplash.com/photo-1557264337-e8a93017fe92?w=600&q=80", body:["The Han River at night has a quality that is almost impossible to describe but immediately recognisable once seen.","K-Pop directors have understood this for years. The river appears in videos by BTS, IU, BLACKPINK, and dozens of others.","We walked both banks with a music video location scout."] },
  { id:7, cats:["food"], type:"article", views:6540, title:"Eating Your Way Through a K-Drama", sub:"The tteokbokki stalls, pojangmacha tents, and late-night ramyun spots that made it on screen.", time:"7 min read", imgH: 300, thumb:"https://images.unsplash.com/photo-1635363638580-c2809d049eee?w=600&q=80", body:["Korean dramas have always understood that food is not decoration — it is emotion made edible.","Many scenes were filmed in real restaurants that still operate.","ATO has mapped twelve real filming locations where the food is as good as the scenery."] },
  { id:8, cats:["drama","place"], type:"article", views:5900, title:"The Real Seoul of Squid Game: Beyond the Set", sub:"Hwang Dong-hyuk chose these locations deliberately. Here's why each one matters.", time:"8 min read", imgH: 220, thumb:"https://images.unsplash.com/photo-1601621915196-2621bfb0cd6e?w=600&q=80", body:["Most people assume Squid Game was filmed entirely on constructed sets. But the establishing scenes were shot in real places.","Baekun Market in Ssangmun-dong is one of them. It's a working traditional market.","We visited on a Tuesday morning. Nobody mentioned the show. The ordinariness was exactly the point."] },
  { id:9, cats:["beauty"], type:"article", views:4200, title:"Seoul Skincare Ingredients Worth Bringing Home", sub:"Snail mucin, centella, mugwort — what actually works and where to find it.", time:"5 min read", imgH: 340, thumb:"https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=600&q=80", body:["Korean skincare isn't a trend — it's a philosophy.","The ingredients that have attracted the most serious attention are centella asiatica and snail secretion filtrate.","The best places to find high-concentration formulations are not in the tourist shopping districts."] },
];

export const TRAILS = [
  { id:101, cats:["music","place"], type:"trail", views:10400, title:"Spring Day — Iryeong Station", location:"Yangju, Gyeonggi-do", tag:"Music · BTS Spring Day", imgH:340, desc:"An abandoned station since 2004, immortalised in BTS's 'Spring Day'. Only ARMY pilgrims come now — and the wind, and the light, and the memory of V standing alone.", thumb:"https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=600&q=80", youtube:"xEeFrLSkMm8", mapQuery:"경기도 양주 이령역" },
  { id:102, cats:["film","place"], type:"trail", views:9100, title:"Jahamun Tunnel Stairs", location:"Buam-dong, Jongno-gu", tag:"Film · Parasite (Oscar Winner)", imgH:260, desc:"The dramatic staircase where the Ki-taek family fled through pouring rain. A photo zone marks the exact spot. One of Seoul's most quietly powerful places.", thumb:"https://images.unsplash.com/photo-1607893378714-007fd47c8719?w=600&q=80", youtube:"isOGD_7hNIY", mapQuery:"서울 종로구 자하문로 219 자하문터널 계단" },
  { id:103, cats:["drama","place"], type:"trail", views:8800, title:"Bukchon Hanok Village", location:"Jongno-gu, Seoul", tag:"Netflix · Crash Landing on You", imgH:300, desc:"600-year-old tile-roofed alleys — the backdrop for Crash Landing on You. Golden-hour light through the rooftops is still exactly as the cameras captured it.", thumb:"https://img.youtube.com/vi/sakIHiQDn5g/hqdefault.jpg", youtube:"sakIHiQDn5g", mapQuery:"서울 종로구 북촌한옥마을" },
  { id:104, cats:["music","place"], type:"trail", views:7900, title:"BTS Butter Bridge", location:"Mapo-gu, Seoul", tag:"Music · BTS Butter (Billboard #1)", imgH:220, desc:"BTS performed 'Butter' on this empty bridge for The Tonight Show. After sunset, Han River lights shimmer below — fans have never stopped coming.", thumb:"https://images.unsplash.com/photo-1557264337-e8a93017fe92?w=600&q=80", youtube:"WMweEpGlu_U", mapQuery:"서울 마포구 월드컵대교" },
  { id:105, cats:["drama","place"], type:"trail", views:7600, title:"Squid Game Alley", location:"Ssangmun-dong, Seoul", tag:"Netflix · Squid Game", imgH:280, desc:"Walk through the iconic neighborhood of Seong Ki-hoon. Baekun Market still buzzes with the same locals who watched a global phenomenon unfold.", thumb:"https://images.unsplash.com/photo-1601621915196-2621bfb0cd6e?w=600&q=80", youtube:"oqxAJKy0ii4", mapQuery:"서울 도봉구 백운시장" },
  { id:106, cats:["film","food"], type:"trail", views:6300, title:"Parasite — The Real Streets", location:"Ahyeon-dong, Mapo-gu", tag:"Film · Parasite (Cannes Palme d'Or)", imgH:360, desc:"Bong Joon-ho filmed in real Seoul back-alleys. Visit the actual Daejissal Supermarket and the staircase from the iconic rainy-night escape.", thumb:"https://images.unsplash.com/photo-1535189043414-47a3c49a0bed?w=600&q=80", youtube:"isOGD_7hNIY", mapQuery:"서울 마포구 손기정로 32 돼지쌀슈퍼" },
];

export const POPULAR_ARTICLES = [...ARTICLES].sort((a, b) => b.views - a.views);
export const POPULAR_TRAILS   = [...TRAILS].sort((a, b) => b.views - a.views);
export const FEATURED         = POPULAR_ARTICLES[0];
export const HERO_GRID        = ["drama", "film", "music", "beauty"].map(cat =>
  ARTICLES.filter(a => a.cats.includes(cat)).sort((a, b) => b.views - a.views)[0]
);
