'use client';
import { useState, useEffect, useRef } from "react";
import { NAV_CATS, NAV_SECTIONS, ARTICLES, TRAILS, POPULAR_ARTICLES, POPULAR_TRAILS, FEATURED, HERO_GRID } from "./data.js";
import './styles.css';
import { MasonryGrid, MasonryItem } from "./components/MasonryGrid";
import Carousel from "./components/Carousel";
import App from "./App";
import Header from "./components/Header";
import SecHead from "./components/SecHead";
import ArticleModal from "./components/ArticleModal";
import TrailsDrawer from "./components/TrailsDrawer";
import ArticlePin from "./components/ArticlePin";
import TrailPin from "./components/TrailPin";
import HomePage from "./components/HomePage";
import PageHead from "./components/PageHead";
import EditPage from "./components/EditPage";
import TrailPage from "./components/TrailPage";
import CatPage from "./components/CatPage";

export default App;